export const languageOptions = [
  "JavaScript",
  "Python",
  "Java",
  "PHP",
  "TypeScript",
  "C++",
  "C",
  "Go",
  "Rust",
  "Kotlin",
  "Ruby",
  "Dart",
  "Swift",
];

export const licenseOptions = [
  "MIT License",
  "Apache License 2.0",
  "GNU General Public License (GPL) 2.0",
  "GNU General Public License (GPL) 3.0",
  "GNU Lesser General Public License (LGPL) 2.1",
  "GNU Lesser General Public License (LGPL) 3.0",
  "Mozilla Public License 2.0",
  "BSD 2-Clause 'Simplified' License",
  "BSD 3-Clause 'New' or 'Revised' License",
  "Creative Commons Zero v1.0 Universal (CC0 1.0)",
  "Eclipse Public License 2.0",
  "Eclipse Public License 1.0",
  "Microsoft Public License (MS-PL)",
  "The Unlicense",
  "Artistic License 2.0",
  "European Union Public License (EUPL) 1.1",
  "GNU Affero General Public License (AGPL) 3.0",
  "Zlib License",
  "ISC License",
  "Academic Free License v3.0",
  "Beerware License",
  "Boost Software License 1.0",
  "Common Development and Distribution License (CDDL) 1.0",
  "Common Public License 1.0",
  "IBM Public License 1.0",
  "Lucent Public License Version 1.02",
  "NCSA Open Source License",
  "Open Software License 3.0",
  "PHP License v3.01",
  "Python Software Foundation License",
  "SIL Open Font License 1.1",
  "Sun Public License 1.0",
  "Universal Permissive License (UPL) 1.0",
  "Vim License",
  "WTFPL (Do What The F*ck You Want To Public License)",
  "zlib/libpng License",
];

export const modelOptions = [
  "gpt-4o",
  "gpt-4o-2024-05-13",
  "gpt-4-turbo",
  "gpt-4-turbo-2024-04-09",
  "gpt-4-turbo-preview",
  "gpt-4-0125-preview",
  "gpt-4-1106-preview",
  "gpt-4-vision-preview",
  "gpt-4",
  "gpt-4-0613",
  "gpt-4-32k",
  "gpt-4-32k-0613",
  "gpt-3.5-turbo-0125",
  "gpt-3.5-turbo",
  "gpt-3.5-turbo-1106",
  "gpt-3.5-turbo-16k",
  "gpt-3.5-turbo-0613",
  "gpt-3.5-turbo-16k-0613",
];

export const languageRecommendationOptions = ["1", "2", "3", "4", "5"];
